### ISSUE TITLE
Fatal error: Class 'SqlFormatter' not found

### ISSUE THREAD

**Issue by GabbroWick** [sarfraznawaz2005/VisualQuery#1]
I've install your app, but I get this error when select a table from the left sidebar:

Fatal error: Class 'SqlFormatter' not found in /var/www/html/app/controllers/table.php on line 68

**Comment by GabbroWick** [comment]
I've solved by myself. In autoload.php the classes are loaded in lower case, but the file is named with first upper case, so i renamed the file app/classes/SqlFormatter.php in sqlformatter.php

**Comment by sarfraznawaz2005** [comment]
yes that was the actual issue. Thanks

Regards,
Sarfraz http://sarfraznawaz.wordpress.com
