### ISSUE TITLE
how to install in ubuntu

### ISSUE THREAD

**Issue by saikatkoley** [sarfraznawaz2005/VisualQuery#4]
I just put the folder into /var/www/html/practice/visualquery
and set up the database in config.php file. Now what should i do?

Page is showing 404 error page not found

**Comment by sarfraznawaz2005** [comment]
Iam not sure, make sure .htaccess file is being read by apache and that `mod_rewrite` module is enabled. If you are using nginx instead of apache then you will need to modify contents of htaccess file accordingly so that all requests go through index.php file.

**Comment by saikatkoley** [comment]
Not working in case of Linux and also not in wamp. Please provide a step for wamp please.

**Comment by noeldum** [comment]
same here on Ubuntu too. Getting the message below when opening the browser to this.

404 Not Found
