### ISSUE TITLE
Uncaught PDOException: could not find driver in C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php:

### ISSUE THREAD

**Issue by Github743** [sarfraznawaz2005/VisualQuery#5]
Getting the error as below when I run the code

Fatal error: Uncaught PDOException: could not find driver in C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php:253 Stack trace: #0 C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php(253): PDO->__construct('mysql:host=test...', 'root', '1234', NULL) #1 C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php(369): ORM::_setup_db('default') #2 C:\inetpub\wwwroot\VisualQuery-master\index.php(63): ORM::get_db() #3 {main} thrown in C:\inetpub\wwwroot\VisualQuery-master\vendor\j4mie\idiorm\idiorm.php on line 253

**Comment by sarfraznawaz2005** [comment]
I belive you have not turned on pdo driver from php.ini file, plz see this:

https://stackoverflow.com/questions/2852748/pdoexception-could-not-find-driver
